### ISSUE TITLE
Ship checklist for AWS provider

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi-aws#130]
- Good examples
    * Improve `serverless-raw` example (tracking in https://github.com/pulumi/pulumi-aws/issues/166)
    * Other larger examples can live in `pulumi-examples` repo.
- Attempt to minimize future breaking changes
    * [ ] Simplify generated type names (remove repetition in type name) (tracked in https://github.com/pulumi/pulumi-aws/issues/167)
    * [x] Accept strongly typed inputs as options, not replacements (and project as raw type on output)
    * [x] Remove `getLinuxAMI`
    * [x] Pluralize and project nested structs properly
- API and overlay consistency (largely work to continue to do over time)
    * [x] Add `Sourced From...` to docs.
    * [ ] Document design guidelines (directional goals for how we type libraries, which we can improve over time as much as possible without making breaking changes). (tracking at https://github.com/pulumi/home/wiki/API-design-for-TF-bridge-based-Pulumi-pacakges)
