### ISSUE TITLE
[Epic] Pulumi AWS 6.0

### ISSUE THREAD

**Issue by kpitzen** [pulumi/pulumi-aws#2539]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The upstream terraform AWS provider has been upgraded to the next major version - this introduces a number of breaking changes to the provider which we will track here. Additionally, there are a number of outstanding issues reported with that version of the upstream provider which we will use as a gate to inform when 6.0 is ready to be moved out of pre-release and into a full release.

Breaking changes:
https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.0.0

Tasks:
- [x] https://github.com/pulumi/pulumi-aws/issues/2547
- [x] https://github.com/pulumi/pulumi-aws/issues/2548
- [x] Reintroduce  aws_quicksight_namespace commented out in https://github.com/pulumi/pulumi-aws/pull/2557 
   - [x] Fixed by https://github.com/pulumi/pulumi-aws/pull/2574
- [x] https://github.com/pulumi/pulumi-aws/issues/2549
  - [x] Fixed https://github.com/pulumi/pulumi-aws/issues/2533
- [x] https://github.com/pulumi/pulumi-aws/issues/2602
- [x] https://github.com/pulumi/pulumi-aws/issues/2568
- [x] https://github.com/pulumi/pulumi-aws/issues/2607
- [x] https://github.com/pulumi/pulumi-aws/pull/2597
- [x] https://github.com/pulumi/pulumi-aws/pull/2613
- [x] https://github.com/pulumi/pulumi-aws/pull/2615
- [x] pulumi/pulumi-aws#2616
- [x] https://github.com/pulumi/pulumi-aws/issues/1038
- [x] https://github.com/pulumi/pulumi-aws/issues/2626
- [x] https://github.com/pulumi/pulumi-aws-apigateway/issues/82
- [x] https://github.com/pulumi/pulumi-aws/issues/2639
- [x] https://github.com/pulumi/pulumi-aws/issues/2633
- [x] https://github.com/pulumi/pulumi-aws/issues/2644
- [x] https://github.com/pulumi/pulumi-aws/issues/2646
- [x] https://github.com/pulumi/pulumi-aws/issues/2663
- [x] https://github.com/pulumi/pulumi-aws/issues/2550
- [x] https://github.com/pulumi/pulumi-aws/issues/2650
- [x] https://github.com/pulumi/pulumi-aws/issues/2665
- [x] https://github.com/pulumi/pulumi-aws/issues/2658
- [x] https://github.com/pulumi/pulumi-terraform-bridge/issues/1021
- [x] #2674
- [x] https://github.com/pulumi/pulumi-aws/issues/2664
- [x] https://github.com/pulumi/pulumi-aws/issues/2626
-1423 [x] #2710
- [x] https://github.com/pulumi/pulumi-aws/issues/2546

Moved post-release tasks to https://github.com/pulumi/pulumi-aws/issues/2753

#### Upstream issues

- [x] https://github.com/hashicorp/terraform-provider-aws/issues/31633
- [ ] https://github.com/hashicorp/terraform-provider-aws/issues/31623
- [ ] https://github.com/hashicorp/terraform-provider-aws/issues/31659
- [x] https://github.com/hashicorp/terraform-provider-aws/issues/31594

#### Dependent issues
- https://github.com/pulumi/pulumi-aws/issues/2662
- https://github.com/pulumi/pulumi-aws/issues/1423

**Comment by t0yv0** [comment]
It would be helpful if we could move https://github.com/pulumi/pulumi-terraform-bridge/issues/830 here or close it I understand the plan is to roll it out with the alpha simultaneously. Per conversation with @AaronFriel I will be closing https://github.com/pulumi/pulumi-terraform-bridge/issues/981 where 830 is the one remaining item.

**Comment by WillDaSilva** [comment]
Looks like the release job failed to publish v6.0.0 of the Python SDK because the release had previously been made, then yanked: https://github.com/pulumi/pulumi-aws/actions/runs/5810390834/job/15754847261

I suspect you'll want to release a post/patch version, as I don't believe the v6.0.0 files that were uploaded to PyPI can be changed.

**Comment by aureq** [comment]
@iwahbe do we have an understanding of the breaking changes (if any) for this release please?

**Comment by aureq** [comment]
Thanks @iwahbe 
Do you think it could be helpful if we were providing that link as part of the GitHub release as well?
