### ISSUE TITLE
[EPIC] Tests should be runnable with minimal setup

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi-aws#2667]
## Background

Trying to run program tests locally can be quite challenging.

1. To test Go programs, you must set `PULUMI_GO_DEP_ROOT` to the path of the directory above the repository.
2. To test node, dotnet or python programs you must run `make install_nodejs` first.
3. Any changes to the schema require re-running `make install_[LANG]`.
4. You must build the provider binary manually before running any tests.
5. You must ensure the built provider binary is on the path and is not hidden by any other binaries
6. Failure to set up the PATH correctly will not always result in test failure but will run the tests against a different binary silently.
7. You must provide crentials for AWS

## Specific aims

The ideal user flow should be:
1. Checkout repository
2. Run `make`
3. Authenticate with the cloud provider (`aws sso login`)
4. Run tests via IDE or command line

Specific fixes:
- [ ] `PULUMI_GO_DEP_ROOT` should be set automatically within the test (or the need for it should be removed in the program test library).
- [ ] We should never resolve the provider binary via the PATH. We should use `LocalProviders` (see Appendix A)
- [ ] You should not have to re-run make commands to ensure SDKs are "installed". This should be done in the test setup (ideally by the program test library).

## Appendix A: Using LocalProviders

```go
func getBaseOptions(t *testing.T) integration.ProgramTestOptions {
	binPath, err := filepath.Abs("../bin")
	...
	return integration.ProgramTestOptions{
		...
		LocalProviders: []integration.LocalDependency{
			{
				Package: "azure-native",
				Path:    binPath,
			},
		},
	}
}
```

**Comment by iwahbe** [comment]
@danielrbradley I have never set `PULUMI_GO_DEP_ROOT` and I can run go tests fine.

**Comment by danielrbradley** [comment]
@iwahbe I think this is dependent on which directory you use to check out your code.

**Comment by iwahbe** [comment]
> @iwahbe I think this is dependent on which directory you use to check out your code.

It could be a `GOPATH` thing. I have no issue believing that.

**Comment by t0yv0** [comment]
Don't forget the build tags (need for `-tags all`) that makes IDEs unable to do completion in test files unless you do something special.
