### ISSUE TITLE
Tracking Pulumi AWS 6.0.0 release deprecation

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-aws#2683]
In light of #2682, we are removing the 6.0 release to root cause the replacement of existing resources during an upgrade.

```[tasklist]
### Tasks
- [x] [Node.js / NPM](https://www.npmjs.com/package/@pulumi/aws)
- [x] [Python / PyPI](https://pypi.org/project/pulumi-aws/)
- [x] [.NET / NuGet](https://www.nuget.org/packages/Pulumi.Aws/)
- [x] Go - [pkg.go.dev has already mirrored v6.0.0](https://pkg.go.dev/github.com/pulumi/pulumi-aws/sdk/v6/go/aws), will need to retract 6.0.0
- [x] [Java / Maven Central](https://issues.sonatype.org/browse/MVNCENTRAL-8266), [JIRA support issue](https://issues.sonatype.org/browse/MVNCENTRAL-8266)
- [x] GitHub Release
- [x] Binaries
- [x] Pulumi Registry docs - [Revert PR](https://github.com/pulumi/registry/pull/2987)
- [x] Revert templates
```

**Comment by mikhailshilkov** [comment]
We need to revert https://www.pulumi.com/registry/packages/aws/api-docs too

**Comment by t0yv0** [comment]
Delisting succeeded for NPM. ON `pulumi new aws-typescript`:

```
[255] t0yv0@Antons-MacBook-Pro> npm i                                                  ~/tmp/2023/08/p0-aws6
npm WARN deprecated @pulumi/aws@6.0.0: Deprecating 6.0.0 due to a critical issue, we recommend continue using 5.x. See: https://github.com/pulumi/pulumi-aws/issues/2682

removed 20 packages, changed 1 package, and audited 200 packages in 3s

65 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
t0yv0@Antons-MacBook-Pro> pulumi preview                                               ~/tmp/2023/08/p0-aws6
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/t0yv0/p0-aws6/dev/previews/d7f8a7d3-f497-4592-ac19-ce3a7241d3d7

     Type                     Name           Plan       Info
 +   pulumi:pulumi:Stack      p0-aws6-dev    create     
     └─ pulumi:providers:aws  default_6_0_0             1 error


Diagnostics:
  pulumi:providers:aws (default_6_0_0):
    error: Could not automatically download and install resource plugin 'pulumi-resource-aws' at version v6.0.0, install the plugin using `pulumi plugin install resource aws v6.0.0`: error downloading provider aws to file: failed to download plugin: aws-6.0.0: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-aws-v6.0.0-darwin-amd64.tar.gz


```

**Comment by AaronFriel** [comment]
@t0yv0 just in case, I checked the AWS TypeScript template:

```sh
$ cat package.json 
{
    "name": "tmp.DEWSLbsUH0",
    "main": "index.ts",
    "devDependencies": {
        "@types/node": "^16"
    },
    "dependencies": {
        "@pulumi/pulumi": "^3.0.0",
        "@pulumi/aws": "^5.0.0",
        "@pulumi/awsx": "^1.0.0"
    }
}
```

Did you get 6.0 by default or did you edit the template?

**Comment by t0yv0** [comment]
Oh right I edited the template.

**Comment by t0yv0** [comment]
Thanks for checking!

**Comment by t0yv0** [comment]
Go is retracted, tagged sdk/v6.0.1

**Comment by t0yv0** [comment]
I've restored my access to OSSRH, the creds are in 1password - we should probably switch to company account instead of sharing "t0yv0" creds, however I can't view https://issues.sonatype.org/browse/MVNCENTRAL-8266 support issue - no permissions. The rest seems done. @AaronFriel can you follow up on the issue since it's under your personal account. Thank you.

**Comment by AaronFriel** [comment]
Maven Central / Sonatype has a policy against removing artifacts:

> Sonatype policy prohibits the removal or any other modification of artifacts after they've been released. For details on this long-standing policy, have a look here:
> https://central.sonatype.org/faq/can-i-change-a-component/
> In cases like this, we recommend that you publish a new, corrected version and inform your users to avoid the incorrect version.
