### ISSUE TITLE
[Epic] Post AWS 6.0 Release Tasks

### ISSUE THREAD

**Issue by mnlumi** [pulumi/pulumi-aws#2753]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

This epic tracks follow-up items after shipping AWS 6.0 https://github.com/pulumi/pulumi-aws/issues/2539.

Release tasks:
- [x] pulumi/pulumi-aws#2620
- [x] pulumi/pulumi-aws#2621
- [x] pulumi/templates#618
- [ ] Pulumi-service update (post release)
- [x] Post to community slack

Post-Release tasks:
- [ ] https://github.com/pulumi/pulumi-awsx/issues/1052
- [x] pulumi/pulumi-eks#902
- [x] pulumi/pulumi-aws-apigateway#84
- [x] pulumi/pulumi-awsx#1068
- [ ] Update remaining examples to 6.0 that use awsx
- [ ] Update remaining templates to 6.0 that use awsx

Related:
- [ ] https://github.com/pulumi/pulumi-hugo/pull/3325
- [ ] https://github.com/pulumi/registry/issues/3085
- [ ] https://github.com/pulumi/docs/issues/9764
