### ISSUE TITLE
Release checklist for 6.0.3

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-aws#2762]
- [ ] https://github.com/pulumi/pulumi-aws/pull/2761
- [ ] https://github.com/pulumi/pulumi-aws/issues/2760
- [x] upgrade bridge to apply https://github.com/pulumi/pulumi-terraform-bridge/pull/1345
- [x] https://github.com/pulumi/pulumi-aws/pull/2681

**Comment by t0yv0** [comment]
@iwahbe does this look accurate? Anything else we need to include?

**Comment by t0yv0** [comment]
So 6.0.3 got released with part of these, closing. 2760 and 2761 will make it into the next release.
