### ISSUE TITLE
Epic: Lambda Builders

### ISSUE THREAD

**Issue by corymhall** [pulumi/pulumi-aws#3980]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Tracking issue for enabling [Lambda Builders](https://github.com/aws/aws-lambda-builders) to be consumed seamlessly from Pulumi programs as a component.

```[tasklist]
### Tasks
- [ ] Create component library repo and enroll in ci-mgmt
- [ ] Write the base implementation and publish the first builder for Go
- [ ] Publish builder for Java
- [ ] Publish builder for Python
- [ ] Publish builder for Ruby
- [ ] Publish builder for Dotnet
- [ ] Publish builder for Makefile
- [ ] Publish builder for Nodejs
- [ ] Publish builder for Nodejs-Esbuild
- [ ] Publish builder for Rust
- [ ] Update documentation & Examples
```
