### ISSUE TITLE
Catalog existing integration tests

### ISSUE THREAD

**Issue by corymhall** [pulumi/pulumi-aws#4282]
Need to catalog existing integration tests.

```[tasklist]
### Tasks
- [ ] Move examples smoke test integration tests to pulumi-examples (where possible). 
- [ ] Run Examples smoke tests infrequently (prior to release?) and not on every PR.
- [ ] Move regression tests to  pulumi-terraform-bridge or pu/pu where applicable.
- [ ] Expand coverage of the true integration tests to cover all scenarios
- [ ] Write testing guide based on results
```

**Comment by corymhall** [comment]
Done https://www.notion.so/Pulumi-AWS-Examples-Test-Audit-345fdbdf1cce8165bfc4d0f325f4503e
